[package]
name = "leptos_meta"
version = "0.1.0-alpha"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Tools to set HTML metadata in the Leptos web framework."

[dependencies]
cfg-if = "1"
leptos = { path = "../leptos", default-features = false }
typed-builder = "0.11"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlLinkElement", "HtmlMetaElement", "HtmlTitleElement"]

[features]
default = ["csr"]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
stable = ["leptos/stable"]

[package.metadata.cargo-all-features]
denylist = ["stable"]
